CREATE TABLE todos (
    id INT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    item_order INT,
    completed BOOLEAN NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
